export const modalsConstants = {
    OPEN_DONATE_MODAL: 'OPEN_DONATE_MODAL',

    OPEN_IMAGE_MODAL: 'OPEN_IMAGE_MODAL',
    CLOSE_IMAGE_MODAL: 'CLOSE_IMAGE_MODAL',

    OPEN_REFERAL_MODAL: 'OPEN_REFERAL_MODAL',
};
