export const notificationsConstants = {
    PUSH_NOTIFICATION: 'PUSH_NOTIFICATION',

    GET_ALL_NOTIFICATIONS_REQUEST: 'GET_ALL_NOTIFICATIONS_REQUEST',
    GET_ALL_NOTIFICATIONS_SUCCESS: 'GET_ALL_NOTIFICATIONS_SUCCESS',
    GET_ALL_NOTIFICATIONS_FAILURE: 'GET_ALL_NOTIFICATIONS_FAILURE',

    MARK_AS_READ_ONE_BY_ID_NOTIFICATIONS_REQUEST: 'MARK_AS_READ_ONE_BY_ID_NOTIFICATIONS_REQUEST',
    MARK_AS_READ_ONE_BY_ID_NOTIFICATIONS_SUCCESS: 'MARK_AS_READ_ONE_BY_ID_NOTIFICATIONS_SUCCESS',
    MARK_AS_READ_ONE_BY_ID_NOTIFICATIONS_FAILURE: 'MARK_AS_READ_ONE_BY_ID_NOTIFICATIONS_FAILURE',

    MARK_AS_READ_ALL_NOTIFICATIONS_REQUEST: 'MARK_AS_READ_ALL_NOTIFICATIONS_REQUEST',
    MARK_AS_READ_ALL_NOTIFICATIONS_SUCCESS: 'MARK_AS_READ_ALL_NOTIFICATIONS_SUCCESS',
    MARK_AS_READ_ALL_NOTIFICATIONS_FAILURE: 'MARK_AS_READ_ALL_NOTIFICATIONS_FAILURE',
};
