export const usersReviewsConstants = {
    USERS_REVIEWS_INIT: 'USERS_REVIEWS_INIT',

    CREATE_USERS_REVIEWS_REQUEST: 'CREATE_USERS_REVIEWS_REQUEST',
    CREATE_USERS_REVIEWS_SUCCESS: 'CREATE_USERS_REVIEWS_SUCCESS',
    CREATE_USERS_REVIEWS_FAILURE: 'CREATE_USERS_REVIEWS_FAILURE',

    UPDATE_USERS_REVIEWS_REQUEST: 'UPDATE_USERS_REVIEWS_REQUEST',
    UPDATE_USERS_REVIEWS_SUCCESS: 'UPDATE_USERS_REVIEWS_SUCCESS',
    UPDATE_USERS_REVIEWS_FAILURE: 'UPDATE_USERS_REVIEWS_FAILURE',

    DELETE_USERS_REVIEWS_REQUEST: 'DELETE_USERS_REVIEWS_REQUEST',
    DELETE_USERS_REVIEWS_SUCCESS: 'DELETE_USERS_REVIEWS_SUCCESS',
    DELETE_USERS_REVIEWS_FAILURE: 'DELETE_USERS_REVIEWS_FAILURE',

    GET_ALL_USERS_REVIEWS_REQUEST: 'GET_ALL_USERS_REVIEWS_REQUEST',
    GET_ALL_USERS_REVIEWS_SUCCESS: 'GET_ALL_USERS_REVIEWS_SUCCESS',
    GET_ALL_USERS_REVIEWS_FAILURE: 'GET_ALL_USERS_REVIEWS_FAILURE',

    GET_ONE_BY_ID_USERS_REVIEWS_REQUEST: 'GET_ONE_BY_ID_USERS_REVIEWS_REQUEST',
    GET_ONE_BY_ID_USERS_REVIEWS_SUCCESS: 'GET_ONE_BY_ID_USERS_REVIEWS_SUCCESS',
    GET_ONE_BY_ID_USERS_REVIEWS_FAILURE: 'GET_ONE_BY_ID_USERS_REVIEWS_FAILURE',
};
