export const organizationsConstants = {
    CREATE_ORGANIZATION_REQUEST: 'CREATE_ORGANIZATION_REQUEST',
    CREATE_ORGANIZATION_SUCCESS: 'CREATE_ORGANIZATION_SUCCESS',
    CREATE_ORGANIZATION_FAILURE: 'CREATE_ORGANIZATION_FAILURE',

    UPDATE_ORGANIZATION_REQUEST: 'UPDATE_ORGANIZATION_REQUEST',
    UPDATE_ORGANIZATION_SUCCESS: 'UPDATE_ORGANIZATION_SUCCESS',
    UPDATE_ORGANIZATION_FAILURE: 'UPDATE_ORGANIZATION_FAILURE',

    DELETE_ORGANIZATION_REQUEST: 'DELETE_ORGANIZATION_REQUEST',
    DELETE_ORGANIZATION_SUCCESS: 'DELETE_ORGANIZATION_SUCCESS',
    DELETE_ORGANIZATION_FAILURE: 'DELETE_ORGANIZATION_FAILURE',

    GET_ALL_ORGANIZATIONS_REQUEST: 'GET_ALL_ORGANIZATIONS_REQUEST',
    GET_ALL_ORGANIZATIONS_SUCCESS: 'GET_ALL_ORGANIZATIONS_SUCCESS',
    GET_ALL_ORGANIZATIONS_FAILURE: 'GET_ALL_ORGANIZATIONS_FAILURE',

    GET_ONE_BY_ID_ORGANIZATION_REQUEST: 'GET_ONE_BY_ID_ORGANIZATION_REQUEST',
    GET_ONE_BY_ID_ORGANIZATION_SUCCESS: 'GET_ONE_BY_ID_ORGANIZATION_SUCCESS',
    GET_ONE_BY_ID_ORGANIZATION_FAILURE: 'GET_ONE_BY_ID_ORGANIZATION_FAILURE',
};
