export const organizationsTypesConstants = {
    GET_ALL_ORGANIZATIONS_TYPES_REQUEST: 'GET_ALL_ORGANIZATIONS_TYPES_REQUEST',
    GET_ALL_ORGANIZATIONS_TYPES_SUCCESS: 'GET_ALL_ORGANIZATIONS_TYPES_SUCCESS',
    GET_ALL_ORGANIZATIONS_TYPES_FAILURE: 'GET_ALL_ORGANIZATIONS_TYPES_FAILURE',
};
