export const organizationsUsersConstants = {
    CREATE_ORGANIZATIONS_USERS_REQUEST: 'CREATE_ORGANIZATIONS_USERS_REQUEST',
    CREATE_ORGANIZATIONS_USERS_SUCCESS: 'CREATE_ORGANIZATIONS_USERS_SUCCESS',
    CREATE_ORGANIZATIONS_USERS_FAILURE: 'CREATE_ORGANIZATIONS_USERS_FAILURE',

    DELETE_ORGANIZATIONS_USERS_REQUEST: 'DELETE_ORGANIZATIONS_USERS_REQUEST',
    DELETE_ORGANIZATIONS_USERS_SUCCESS: 'DELETE_ORGANIZATIONS_USERS_SUCCESS',
    DELETE_ORGANIZATIONS_USERS_FAILURE: 'DELETE_ORGANIZATIONS_USERS_FAILURE',
};
