export const statisticConstants = {
    USERS_STATISTIC_REQUEST: 'USERS_STATISTIC_REQUEST',
    USERS_STATISTIC_SUCCESS: 'USERS_STATISTIC_SUCCESS',
    USERS_STATISTIC_FAILURE: 'USERS_STATISTIC_FAILURE',

    COURSES_USERS_PROGRESS_STATISTIC_REQUEST: 'COURSES_USERS_PROGRESS_STATISTIC_REQUEST',
    COURSES_USERS_PROGRESS_STATISTIC_SUCCESS: 'COURSES_USERS_PROGRESS_STATISTIC_SUCCESS',
    COURSES_USERS_PROGRESS_STATISTIC_FAILURE: 'COURSES_USERS_PROGRESS_STATISTIC_FAILURE',

    GET_STATISTIC_BY_COURSE_REQUEST: 'GET_STATISTIC_BY_COURSE_REQUEST',
    GET_STATISTIC_BY_COURSE_SUCCESS: 'GET_STATISTIC_BY_COURSE_SUCCESS',
    GET_STATISTIC_BY_COURSE_FAILURE: 'GET_STATISTIC_BY_COURSE_FAILURE',
};
